from app.models import db, Card

def seed_cards():
    clubs_2 = Card(player_id=1, value=2, image="https://www.improvemagic.com/wp-content/uploads/2020/11/k2.png")
    clubs_3 = Card(player_id=1, value=3, image="https://www.improvemagic.com/wp-content/uploads/2020/11/k3.png")
    clubs_4 = Card(player_id=1, value=4, image="https://www.improvemagic.com/wp-content/uploads/2020/11/k4.png")
    clubs_5 = Card(player_id=1, value=5, image="https://www.improvemagic.com/wp-content/uploads/2020/11/k5.png")
    clubs_6 = Card(player_id=1, value=6, image="https://www.improvemagic.com/wp-content/uploads/2020/11/k6.png")
    clubs_7 = Card(player_id=1, value=7, image="https://www.improvemagic.com/wp-content/uploads/2020/11/k7.png")
    clubs_8 = Card(player_id=1, value=8, image="https://www.improvemagic.com/wp-content/uploads/2020/11/k8.png")
    clubs_9 = Card(player_id=1, value=9, image="https://www.improvemagic.com/wp-content/uploads/2020/11/k9.png")
    clubs_10 = Card(player_id=1, value=10, image="https://www.improvemagic.com/wp-content/uploads/2020/11/k10.png")
    clubs_j = Card(player_id=1, value=11, image="https://www.improvemagic.com/wp-content/uploads/2020/11/kj.png")
    clubs_q = Card(player_id=1, value=12, image="https://www.improvemagic.com/wp-content/uploads/2020/11/kq.png")
    clubs_k = Card(player_id=1, value=13, image="https://www.improvemagic.com/wp-content/uploads/2020/11/kk.png")
    clubs_a = Card(player_id=1, value=14, image="https://www.improvemagic.com/wp-content/uploads/2020/11/ka.png")

    spades_2 = Card(player_id=1, value=2, image="https://www.improvemagic.com/wp-content/uploads/2020/11/p2.png")
    spades_3 = Card(player_id=1, value=3, image="https://www.improvemagic.com/wp-content/uploads/2020/11/p3.png")
    spades_4 = Card(player_id=1, value=4, image="https://www.improvemagic.com/wp-content/uploads/2020/11/p4.png")
    spades_5 = Card(player_id=1, value=5, image="https://www.improvemagic.com/wp-content/uploads/2020/11/p5.png")
    spades_6 = Card(player_id=1, value=6, image="https://www.improvemagic.com/wp-content/uploads/2020/11/p6.png")
    spades_7 = Card(player_id=1, value=7, image="https://www.improvemagic.com/wp-content/uploads/2020/11/p7.png")
    spades_8 = Card(player_id=1, value=8, image="https://www.improvemagic.com/wp-content/uploads/2020/11/p8.png")
    spades_9 = Card(player_id=1, value=9, image="https://www.improvemagic.com/wp-content/uploads/2020/11/p9.png")
    spades_10 = Card(player_id=1, value=10, image="https://www.improvemagic.com/wp-content/uploads/2020/11/p10.png")
    spades_j = Card(player_id=1, value=11, image="https://www.improvemagic.com/wp-content/uploads/2020/11/pj.png")
    spades_q = Card(player_id=1, value=12, image="https://www.improvemagic.com/wp-content/uploads/2020/11/pq.png")
    spades_k = Card(player_id=1, value=13, image="https://www.improvemagic.com/wp-content/uploads/2020/11/pk.png")
    spades_a = Card(player_id=1, value=14, image="https://www.improvemagic.com/wp-content/uploads/2020/11/pa.png")

    hearts_2 = Card(player_id=1, value=2, image="https://www.improvemagic.com/wp-content/uploads/2020/11/s2.png")
    hearts_3 = Card(player_id=1, value=3, image="https://www.improvemagic.com/wp-content/uploads/2020/11/s3.png")
    hearts_4 = Card(player_id=1, value=4, image="https://www.improvemagic.com/wp-content/uploads/2020/11/s4.png")
    hearts_5 = Card(player_id=1, value=5, image="https://www.improvemagic.com/wp-content/uploads/2020/11/s5.png")
    hearts_6 = Card(player_id=1, value=6, image="https://www.improvemagic.com/wp-content/uploads/2020/11/s6.png")
    hearts_7 = Card(player_id=1, value=7, image="https://www.improvemagic.com/wp-content/uploads/2020/11/s7.png")
    hearts_8 = Card(player_id=1, value=8, image="https://www.improvemagic.com/wp-content/uploads/2020/11/s8.png")
    hearts_9 = Card(player_id=1, value=9, image="https://www.improvemagic.com/wp-content/uploads/2020/11/s9.png")
    hearts_10 = Card(player_id=1, value=10, image="https://www.improvemagic.com/wp-content/uploads/2020/11/s10.png")
    hearts_j = Card(player_id=1, value=11, image="https://www.improvemagic.com/wp-content/uploads/2020/11/sj.png")
    hearts_q = Card(player_id=1, value=12, image="https://www.improvemagic.com/wp-content/uploads/2020/11/sq.png")
    hearts_k = Card(player_id=1, value=13, image="https://www.improvemagic.com/wp-content/uploads/2020/11/sk.png")
    hearts_a = Card(player_id=1, value=14, image="https://www.improvemagic.com/wp-content/uploads/2020/11/sa.png")

    diamonds_2 = Card(player_id=1, value=2, image="https://www.improvemagic.com/wp-content/uploads/2020/11/l2.png")
    diamonds_3 = Card(player_id=1, value=3, image="https://www.improvemagic.com/wp-content/uploads/2020/11/l3.png")
    diamonds_4 = Card(player_id=1, value=4, image="https://www.improvemagic.com/wp-content/uploads/2020/11/l4.png")
    diamonds_5 = Card(player_id=1, value=5, image="https://www.improvemagic.com/wp-content/uploads/2020/11/l5.png")
    diamonds_6 = Card(player_id=1, value=6, image="https://www.improvemagic.com/wp-content/uploads/2020/11/l6.png")
    diamonds_7 = Card(player_id=1, value=7, image="https://www.improvemagic.com/wp-content/uploads/2020/11/l7.png")
    diamonds_8 = Card(player_id=1, value=8, image="https://www.improvemagic.com/wp-content/uploads/2020/11/l8.png")
    diamonds_9 = Card(player_id=1, value=9, image="https://www.improvemagic.com/wp-content/uploads/2020/11/l9.png")
    diamonds_10 = Card(player_id=1, value=10, image="https://www.improvemagic.com/wp-content/uploads/2020/11/l10.png")
    diamonds_j = Card(player_id=1, value=11, image="https://www.improvemagic.com/wp-content/uploads/2020/11/lj.png")
    diamonds_q = Card(player_id=1, value=12, image="https://www.improvemagic.com/wp-content/uploads/2020/11/lq.png")
    diamonds_k = Card(player_id=1, value=13, image="https://www.improvemagic.com/wp-content/uploads/2020/11/lk.png")
    diamonds_a = Card(player_id=1, value=14, image="https://www.improvemagic.com/wp-content/uploads/2020/11/la.png")

    db.session.add(clubs_2)
    db.session.add(clubs_3)
    db.session.add(clubs_4)
    db.session.add(clubs_5)
    db.session.add(clubs_6)
    db.session.add(clubs_7)
    db.session.add(clubs_8)
    db.session.add(clubs_9)
    db.session.add(clubs_10)
    db.session.add(clubs_j)
    db.session.add(clubs_q)
    db.session.add(clubs_k)
    db.session.add(clubs_a)

    db.session.add(spades_2)
    db.session.add(spades_3)
    db.session.add(spades_4)
    db.session.add(spades_5)
    db.session.add(spades_6)
    db.session.add(spades_7)
    db.session.add(spades_8)
    db.session.add(spades_9)
    db.session.add(spades_10)
    db.session.add(spades_j)
    db.session.add(spades_q)
    db.session.add(spades_k)
    db.session.add(spades_a)

    db.session.add(hearts_2)
    db.session.add(hearts_3)
    db.session.add(hearts_4)
    db.session.add(hearts_5)
    db.session.add(hearts_6)
    db.session.add(hearts_7)
    db.session.add(hearts_8)
    db.session.add(hearts_9)
    db.session.add(hearts_10)
    db.session.add(hearts_j)
    db.session.add(hearts_q)
    db.session.add(hearts_k)
    db.session.add(hearts_a)

    db.session.add(diamonds_2)
    db.session.add(diamonds_3)
    db.session.add(diamonds_4)
    db.session.add(diamonds_5)
    db.session.add(diamonds_6)
    db.session.add(diamonds_7)
    db.session.add(diamonds_8)
    db.session.add(diamonds_9)
    db.session.add(diamonds_10)
    db.session.add(diamonds_j)
    db.session.add(diamonds_q)
    db.session.add(diamonds_k)
    db.session.add(diamonds_a)

    db.session.commit()


def undo_cards():
    db.session.execute('TRUNCATE cards RESTART IDENTITY CASCADE;')
    db.session.commit()
